apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/acm-073/test-apps.git
    targetRevision: main
    path: test-charts/nginx
  destination:
    name: in-cluster
    namespace: nginx-prod
